/*
 *  DO NOT MODIFY THIS FILE
 *  This file is generated by this package's build script (package.bld).
 */
/*!
 *  ======== Version ========
 *  Version for the ti.mas.cid package
 */
metaonly module Version inherits ti.mas.swtools.IVersion2 {

    /*
     *  ======== MAJOR ========
     *  Major version number of ti.mas.cid
     */
    override const UInt16 MAJOR = 2;

    /*
     *  ======== MINOR ========
     *  Minor version number of ti.mas.cid
     */
    override const UInt16 MINOR = 2;

    /*
     *  ======== PATCH ========
     *  Patch level of ti.mas.cid
     */
    override const UInt16 PATCH = 1;
    
    /*
     *  ======== BUILD ========
     *  Build Number of ti.mas.cid
     */
    const UInt16 BUILD = 0;
    
    /*
     *  ======== QUALITY ========
     *  Quality level of ti.mas.cid
     */
    override const UInt16 QUALITY = 3;

    /*
     *  ======== BTYPE ========
     *  Built type of ti.mas.cid
     */
    override const UInt16 BTYPE = 0;

  /*
     *  ======== WIDTH ========
     *  Minimum print width for ti.mas.cid
     */
    override const UInt16 WIDTH = 0;

  /*
     *  ======== PACKAGING STD COMPLIANCE ========
     *  Packaging Standard Compliance field
     */
    const UInt16 PKGSTD = 2;    
    
}
